#!/bin/bash

## Center a window using the keyboard
## 
## You can center a window using a keyboard with this script
## https://mxlinux.org/wiki/xfce/xfce-commands-and-other-useful-stuff/

IFS=’x’ read screenWidth screenHeight < <(xdpyinfo | grep dimensions | grep -o ‘[0-9x]*’ | head -n1)

width=$(xdotool getactivewindow getwindowgeometry –shell | head -4 | tail -1 | sed ‘s/[^0-9]*//’)
height=$(xdotool getactivewindow getwindowgeometry –shell | head -5 | tail -1 | sed ‘s/[^0-9]*//’)

newPosX=$((screenWidth/2-width/2))
newPosY=$((screenHeight/2-height/2))

xdotool getactivewindow windowmove “$newPosX” “$newPosY”
